### PR TITLE
Javascript in keyword returns index for arrays; hence points[pos] is required to display point values.

### PR DESCRIPTION
**Pull request by natural-affinity**
Modified polygon function debug info to display points instead of indexes within the array

### CODE REVIEW

**Comment by tnzk** [comment]
@natural-affinity thank you. it looks my silly fault.

**Comment by natural-affinity** [comment]
Not at all, thank you very much for accepting the pull request.  I've been
in enterprise software most of my life, so working with open-source
projects/technologies is a nice change of pace!

P.S. I noticed you built a product called Synclogue.  Are you a startup
company? If you don't mind me asking, how did you get started?  I am also
interested in becoming more of an entrepreneur and building a startup.

Thanks for your time!

Rizwan

**Comment by tnzk** [comment]
Sounds good. I'm also the one who loves to be in the open-source world.

Yes I'm running a startup and I enjoy it so much.
I had found a partner who is good at financials when I'm in school and it had started from there.

Do you also have a startup running or under planning?

**Comment by natural-affinity** [comment]
I did start a company; right now it's service-based (i.e. we will go out
and build products for clients), but I would like to switch it to a
product-based company.

Although I enjoy working with clients in both cases, I feel with a single
product, we can control the direction and technology choices a lot more
rather than 'fitting' the solution to the client's environment.

Company Website:
http://www.rtcodespark.com

**Pull request merged**
